/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

import java.sql.Date;
import java.util.Scanner;
import bitcamp.lms.Lesson;

public class App {
  public static void main(String[] args) {
    
    Scanner keyboard = new Scanner(System.in);
    
    final int LENGTH = 10;
    
    Lesson[] lessons = new Lesson[LENGTH];
    
    int i = 0; // 인덱스 0부터시작
    while (i < LENGTH) {
      Lesson lesson = new Lesson();
      
    System.out.print("번호? ");
    lesson.no = Integer.parseInt(keyboard.nextLine());
    
    System.out.print("수업명? ");
    lesson.name = keyboard.nextLine();
    
    System.out.print("수업내용? ");
    lesson.contents = keyboard.nextLine();
    
    System.out.print("시작일? ");
    lesson.startDate = Date.valueOf(keyboard.nextLine());
    
    System.out.print("종료일? ");
    lesson.endDate = Date.valueOf(keyboard.nextLine());
    
    System.out.print("총수업시간? ");
    lesson.totalHours = Integer.parseInt(keyboard.nextLine());
    
    System.out.println("일수업시간? ");
    lesson.dayHours = Integer.parseInt(keyboard.nextLine());
    
    lessons[i] = lesson;
    i++;
    
    System.out.print("\n계속 하시겠습니까?(Y/N) ");
    String answer = keyboard.nextLine().toLowerCase();
    
    if (!answer.equals("y") && answer.length() > 0) {
      break;
    }
   
    System.out.println();
  }
   
 
    keyboard.close(); 
    
    
    System.out.println();
    
    for (int j = 0; j < i; j++) {
      System.out.printf("%3d, %-15s, %10s ~ %10s, %4d\n",
          lessons[j].no, lessons[j].name, lessons[j].startDate, lessons[j].endDate, lessons[j].totalHours);
    }
  }
}    
