/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App2 {
  public static void main(String[] args) {
    java.util.Scanner keyboard = new java.util.Scanner(System.in);
    java.util.Date today = new java.util.Date();
    
    System.out.print("번호? ");
    int no = keyboard.nextInt();
    
    keyboard.nextLine();
    
    System.out.print("이름? ");
    String name = keyboard.nextLine();
    
    System.out.print("이메일? ");
    String email = keyboard.nextLine();
    
    System.out.print("암호? ");
    int password = keyboard.nextInt();
    
    keyboard.nextLine();
    
    System.out.print("사진? ");
    String picture = keyboard.nextLine();
    
    System.out.print("전화? ");
    String phonenumber = keyboard.nextLine();
    
    System.out.print("가입일? ");
    String enterday = keyboard.nextLine();
    
    System.out.printf("번호: %d\n", no);
    System.out.printf("이름: %s\n", name);
    System.out.printf("이메일: %s\n", email);
    System.out.printf("암호: %d\n", password);
    System.out.printf("사진: %s\n", picture);
    System.out.printf("전화: %s\n", phonenumber);
    System.out.printf("가입일: %s\n", enterday);
    
/*
번호? 1
이름? 홍길동
이메일? hong@test.com
암호? 1111
사진? hong.png
전화? 1111-2222

번호: 1
이름: 홍길동
이메일: hong@test.com
암호: 1111
사진: hong.png
전화: 1111-2222
가입일: 2019-01-01
 */
    }
}
