/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App3 {
  public static void main(String[] args) {
    java.util.Scanner keyboard = new java.util.Scanner(System.in);
    java.util.Date today = new java.util.Date();
   
    System.out.print("번호? ");
    int no = keyboard.nextInt();
    
    keyboard.nextLine();
    
    System.out.print("내용? ");
    String contents = keyboard.nextLine();
    
    System.out.printf("번호: %d\n", no);
    System.out.printf("내용: %s\n", contents);
    
    
    System.out.printf("%1$tY-%1$tm-%1$td\n", today);
    
/*
번호? 1
내용? 게시글입니다.

번호: 1
내용: 게시글입니다.
작성일: 2019-01-01
조회수: 0
 */
   
    }
}
