/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

import java.sql.Date;
import java.util.Scanner;

public class Lesson {
  int no;
  String name;
  String contents;
  Date startDate;
  Date endDate;
  int totalHours;
  int dayHours;
}
