/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

import java.util.Scanner;
import java.sql.Date;

public class Member {
    int no;
    String name;
    String email;
    int password;
    String picture;
    String phoneNumber;
    Date enterDate;
}
