/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

import java.util.Scanner;
import java.sql.Date;
import bitcamp.lms.Member;

public class App2 {
  public static void main(String[] args) {
    Scanner keyboard = new java.util.Scanner(System.in);
    
    final int LENGTH = 10;
    
   Member[] members = new Member[LENGTH];
    
    int i = 0;
    
    while (i < LENGTH) {
      
     Member member = new Member();
     
    System.out.print("번호? ");
    member.no = Integer.parseInt(keyboard.nextLine());
    
    System.out.print("이름? ");
    member.name = keyboard.nextLine();
    
    System.out.print("이메일? ");
    member.email = keyboard.nextLine();
    
    System.out.print("암호? ");
    member.password = Integer.parseInt(keyboard.nextLine());
    
    System.out.print("사진? ");
    member.picture = keyboard.nextLine();
    
    System.out.print("전화? ");
    member.phoneNumber = keyboard.nextLine();
    
    System.out.print("가입일? ");
    member.enterDate = Date.valueOf(keyboard.nextLine());
    
    members[i] = member;
    i++;
    
    System.out.print("\n계속 입력하시겠습니까?(Y/n) ");
    String answer = keyboard.nextLine().toLowerCase();
    
    if (!answer.equals("y") && answer.length() > 0) {
      break;
    }
    
    System.out.println();
    
    }
    keyboard.close();
    
    System.out.println();
    
    for (int j = 0; j < i; j++) {
      System.out.printf("%3d, %-4s, %-20s, %-15s, %s\n", 
          members[j].no, members[j].name, members[j].email, members[j].phoneNumber, members[j].enterDate);
    }
  }    
}
