/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

import java.util.Scanner;
import java.sql.Date;

public class Board {
  int no;
  String contents;
  Date createdDate;
  int viewCount;
}
