/*
 * This Java source file was generated by the Gradle 'init' task
 */

package bitcamp.lms;
// 수업데이터를 저장할 새 데이터 타입
import java.sql.Date;

public class Lesson {
  int no;
  String name;
  String contents;
  Date startDate;
  Date endDate;
  int totalHours;
  int dayHours;
}
