/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App3 {
  public static void main(String[] args) {
    java.util.Scanner keyboard = new java.util.Scanner(System.in);
    java.util.Date today = new java.util.Date();
   
    System.out.print("번호? ");
    int no = keyboard.nextInt();
    
    keyboard.nextLine();
    
    keyboard.close();
    
    System.out.print("내용? ");
    String contents = keyboard.nextLine();
    
    System.out.printf("번호: %d\n", no);
    System.out.printf("내용: %s\n", contents);
    
    
    System.out.printf("%1$tY-%1$tm-%1$td\n", today);
    
/*
번호? 1
내용? 게시글입니다.

번호: 1
내용: 게시글입니다.
작성일: 2019-01-01
조회수: 0

printf(...)
%d 10진법
%o 8진법
%x 16진법
%f 실수형
%s %S 문자형
%tY
%1$d 뒤에오는 아규먼트 중 첫번째(1$)를 선택하겠다는 뜻
%tY 년(4자리)
%ty 년(2자리)
%tm 월
%td 일
%tH 시
%tM 분
%tS 초
%c %C 유니코드문자
%h %H 해시코드표시
 */
   
    }
}
