/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice;

import java.util.Scanner;
import java.sql.Date;

public class AppTest {
    public static void main(String[] args) {
    }
}
