/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice;


public class App05 {
    public static void main(String[] args) {
      String name = System.getProperty("name");
      System.out.println(name);
      // JVM 값이 아예 입력되지 않더라도 null 값이 저장된다.
      // why? 애초에 String name;이 먼저 선언되면서 
      // Heap 메모리가 생기면서 0이 자동으로 입력되기 때문이다.
      
  
  }
}
