/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice;
//java-basic ch05 연습문제.1
import java.util.Scanner;
import java.sql.Date;

public class App01 {
    public static void main(String[] args) {
   // 키보드 입력 스트림(System.in)을 스캐너 객체에 연결한다.
      // => 스캐너는 입력 스트림으로 들어온 문자열을 줄 단위로 잘라주는 역할을 수행한다.
      Scanner keyboard = new Scanner(System.in);

      int[] no = new int[100];
      String[] title = new String[100];
      String[] contents = new String[100];
      Date[] startDate = new Date[100];
      Date[] endDate = new Date[100];
      int[] totalHours = new int[100];
      int[] dayHours = new int[100];

      int index = 0;


      // 콘솔에서 입력 받은 값을 변수에 저장한다.
      while (index < 100) {
      System.out.print("번호? ");
      no[index] = Integer.parseInt(keyboard.nextLine());
      
      System.out.print("수업명? ");
      title[index] = keyboard.nextLine();
      
      System.out.print("설명? ");
      contents[index] = keyboard.nextLine();
      
      System.out.print("시작일? ");
      startDate[index] = Date.valueOf(keyboard.nextLine());
      
      System.out.print("종료일? ");
      endDate[index] = Date.valueOf(keyboard.nextLine());
      
      System.out.print("총수업시간? ");
      totalHours[index] = Integer.parseInt(keyboard.nextLine());
      
      System.out.print("일수업시간? ");
      dayHours[index] = Integer.parseInt(keyboard.nextLine());

      System.out.print("\n계속 입력하시겠습니까?(Y/n)? ");
      String input = keyboard.nextLine();

      index++;

      System.out.println();

      if (!input.equalsIgnoreCase("y"))
        break;
      }
      // 사용후 스캐너 객체의 자원을 해제한다.
      keyboard.close();
      
      System.out.println(); // 빈 줄 출력

      int count = 0;
      
      while (count < index) {
      System.out.printf("%d, %-15s, %s ~ %s, %d\n",
          no[count], title[count], startDate[count], endDate[count], totalHours[count]);
          count++;
      }
    }
  }