/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice;
//java-basic ch05 연습문제.2
import java.util.Scanner;
import java.sql.Date;

public class App02 {
    public static void main(String[] args) {
      Scanner keyboard = new Scanner(System.in);

      int[] no = new int[100];
      String[] name = new String[100];
      String[] email = new String[100];
      String[] password = new String[100];
      String[] photo = new String[100];
      String[] tel = new String[100];
      Date[] registeredDate = new Date[100];

      int index = 0;

      while(index < 100) {
      System.out.print("번호? ");
      no[index] = Integer.parseInt(keyboard.nextLine());
      
      System.out.print("이름? ");
      name[index] = keyboard.nextLine();
      
      System.out.print("이메일? ");
      email[index] = keyboard.nextLine();
      
      System.out.print("암호? ");
      password[index] = keyboard.nextLine();

      System.out.print("사진? ");
      photo[index] = keyboard.nextLine();

      System.out.print("전화? ");
      tel[index] = keyboard.nextLine();

      registeredDate[index] = new Date(System.currentTimeMillis()); 

      index++;

      System.out.print("\n계속 입력하시겠습니까?(Y/n) ");
      String input = keyboard.nextLine();
      System.out.println();

      if (!input.equalsIgnoreCase("y"))
        break;
      }
          
      // 사용후 스캐너 객체의 자원을 해제한다.
      keyboard.close();
      
      System.out.println(); // 빈 줄 출력
      
      int count = 0;
      while (count < index) {
      System.out.printf("%d, %-15s, %-10s, %s, %s\n",
          no[count], name[count], email[count], tel[count], registeredDate[count]);
          count++;
      }
    }
  }