/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice;
// java-basic ch05 연습문제.3
import java.util.Scanner;
import java.sql.Date;

public class App03 {
    public static void main(String[] args) {
      Scanner keyboard = new Scanner(System.in);

      int[] no = new int[100];
      String[] contents = new String[100];
      Date[] createdDate = new Date[100];
      int[] viewCount = new int[100];

      int index = 0;

      while (index < 100) {
      System.out.print("번호? ");
      no[index] = Integer.parseInt(keyboard.nextLine());
      
      System.out.print("내용? ");
      contents[index] = keyboard.nextLine();
      
      createdDate[index] = new Date(System.currentTimeMillis()); 
      
      viewCount[index] = 0;

      index++;

      System.out.print("\n 계속 입력하시겠습니까?(Y/n) ");
      String input = keyboard.nextLine();
      System.out.println();

      if (!input.equalsIgnoreCase("y"))
          break;
      }
      // 사용후 스캐너 객체의 자원을 해제한다.
      keyboard.close();
      
      System.out.println(); // 빈 줄 출력
      
      int count = 0;

      while (count < index) {
      System.out.printf("%d, %s, %s, %d\n",
          no[count], contents[count], createdDate[count], viewCount[count]);
          count++;
      }
    }
  }