/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice;

import java.sql.Date;

public class Lesson {
      int no;
      String title;
      String contents;
      Date startDate;
      Date endDate;
      int totalHours;
      int dayHours;
}