/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice;

import java.sql.Date;

public class Member {
  int no;
  String name;
  String email;
  String password;
  String photo;
  String tel;
  Date registeredDate;
}